name: Record Expected

on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  resolve-image-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.regex-match.outputs.tag_match }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get action.yaml tag
        id: regex-match
        run: |
          action=$(<action.yml)
          regex="jekyll-build-pages:(.*)'"

          if [[ $action =~ $regex ]]
          then
              tag_match="${BASH_REMATCH[1]}"
              echo "tag_match=$tag_match" >> $GITHUB_OUTPUT
          fi

  test-builds:
    needs: resolve-image-tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - simple
          - readme
          - octicons
          - mojombo
          - themes
          - jekyll-include-cache
          - future-false
          - future-true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build local docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: ${{ needs.resolve-image-tag.outputs.tag }}

      - name: Build ${{ matrix.test }} Project
        uses: ./
        with:
          source: ./test_projects/${{ matrix.test }}
          destination: ./test_projects/${{ matrix.test }}/_expected
          build_revision: JEKYLL_BUILD_REVISION
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive ${{ matrix.test }} Project
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.test }}
          path: ./test_projects/${{ matrix.test }}/_expected
