name: "Test"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  resolve-image-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.regex-match.outputs.tag_match }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get action.yaml tag
        id: regex-match
        run: |
          action=$(<action.yml)
          regex="jekyll-build-pages:(.*)'"

          if [[ $action =~ $regex ]]
          then
              tag_match="${BASH_REMATCH[1]}"
              echo "tag_match=$tag_match" >> $GITHUB_OUTPUT
          fi

  test-builds:
    needs: resolve-image-tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - simple
          - readme
          - octicons
          - mojombo
          - themes
          - jekyll-include-cache
          - future-false
          - future-true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build local docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: ${{ needs.resolve-image-tag.outputs.tag }}
      - name: Test ${{ matrix.test }} Project
        uses: ./
        with:
          source: ./test_projects/${{ matrix.test }}
          destination: ./test_projects/${{ matrix.test }}/_site
          build_revision: JEKYLL_BUILD_REVISION
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify output
        run: |
          ./bin/compare_expected_output ./test_projects/${{matrix.test}}
